name: animated_texture
description: A Flutter plugin for simple display of animated textures with customization capability.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
 
  plugin:
    platforms:
      android:
        package: efafi.mostafa.animated_texture
        pluginClass: AnimatedTexturePlugin
      ios:
        pluginClass: AnimatedTexturePlugin
      linux:
        pluginClass: AnimatedTexturePlugin
      macos:
        pluginClass: AnimatedTexturePlugin
      windows:
        pluginClass: AnimatedTexturePluginCApi

  